### ISSUE TITLE
[bug] swap.rug.farm asks users to verify they are on app.rugenerous.exchange

### ISSUE THREAD

**Issue by timothyjlaurent** [RuGenerous/rugenerous-frontend#100]
![image](https://user-images.githubusercontent.com/2000204/144764211-1f7a3480-9dfa-4498-9f22-947f74571f1c.jpeg)

This could cause users to think they're on the incorrect site and dissuade them from using the dex.

**Comment by keeano92** [comment]
Thank you @timothyjlaurent , this is on our internal board as well and will keep you posted on this ticket once a deployment is done addressing this bug.

**Comment by georgetherugger** [comment]
@keeano92 is this issue still relevant? I am not seeing this behavior so wondering if we can close this issue

**Comment by keeano92** [comment]
@georgetherugger Yes this can be closed, this was also for the DEX and this was posted on the front-end which is the DAO. Wrong project altogether.
