### ISSUE TITLE
[Feature/UX] Claim and Auto Stake all bonds

### ISSUE THREAD

**Issue by GhostWalker562** [RuGenerous/rugenerous-frontend#88]
### Summary
New card where a user can click and claim and stake all of their bonds with a single transaction. Not sure if gas is any more expensive than to do it manually, but I've already prototyped a contract and used this feature. I've already deployed a contract (add me Moon#3587 or message me over twitter @pvu_562 to see the tx's) to have it working and claimed my bonds using the smart contract before rebases. Here is the underlying function... 

### Code (ILPBOND == BondDepositoryInterface)
```solidity
  function redeemAndStakeAll(address[] calldata _lpBonds) external {
      uint256 arrayLen = _lpBonds.length;
      for (uint256 i = 0; i < arrayLen; i++) {
          ILPBOND bond = ILPBOND(_lpBonds[i]);
          if (bond.pendingPayoutFor(msg.sender) == 0) continue;
          uint256 val = bond.redeem(msg.sender, false);
          emit BondRedeemed(_lpBonds[i], val);
      }
  }
```

### Solution
If we do it the way I have above, you can adjust what bonds are claimed from the frontend, potentially, you can create check boxes to choose which bonds you want to claim in a single transaction, this might help reduce gas. Anyways, deploying a contract with this function and calling it is so easy. If you give me the go-to, I can hand over the solidity code for you guys to deploy it and I can create the frontend to enable it @keeano92 @camdengrieh.

**Comment by keeano92** [comment]
No Staking.
