### ISSUE TITLE
[Feature] Wrapped Rug

### ISSUE THREAD

**Issue by GhostWalker562** [RuGenerous/rugenerous-frontend#96]
### Summary
For those who want to avoid taxes, they should be able to wrap up their rug into wRUG. It's really easy to do, just fork the wMEMO smart contract and change the address. Basically wMEMO receives the rebases instead of a person and then when they unwrap and the contract will give them the MEMO accordingly, pretty straightforward tbh.

### Solution
File attached (It's a txt because github doesn't allow sol :/)
[wsRug.txt](https://github.com/RuGenerous/rugenerous-frontend/files/7655453/wsRug.txt)

### How to deploy
Just put the sRUG contract address and deploy

**Comment by keeano92** [comment]
Will be taking a look at these as I get back to work tomorrow.  Thanks! 😀

**Comment by GhostWalker562** [comment]
I'm getting started on the frontend too, shouldn't be too difficult

**Comment by keeano92** [comment]
Look forward to seeing some PRs!

**Comment by GhostWalker562** [comment]
Updated the txt with a contract with wsRug instead of wRug

**Comment by GhostWalker562** [comment]
#98

**Comment by keeano92** [comment]
Durag is the final wrapped rug.
